### ISSUE TITLE
User Flow

### ISSUE THREAD

**Issue by adrianv425** [leonprou/genie#3]
How are you expecting to interact with the user's wallet? Will the smart contract simply supply an address for the user to send dai to?

**Comment by leonprou** [comment]
Hey, thanks for opening the first issue here  🤗

Users you mean the players right?
Basically yes. Though not all users need to have a wallet,  just the winners. So when a person is winning, he required to give his Ethereum address (if wasn't supplied before), and he'll get the reward. Until maybe we integrate with off-ramp providers like https://mooni.tech/.

**Comment by adrianv425** [comment]
Got it. I took a look at how you implemented the demo as well and now I understand. Maybe mooni.tech isn't necessary for this hackathon but it would be a great feature in the future. I'm implementing my chess tournament concept and hopefully I'll have a UI up by today. Are there any known issues so far with this repo that I can help with? Good work so far by the way

**Comment by leonprou** [comment]
Sounds great :), yeah agree about Mooni. 
I'm building now a more complicated [demo](https://github.com/leonprou/last-survivor) as a showcase, and to understand the requirements better. Want to launch it this week.

As I deploy Genie, theoretically everyone can use it, though the registration of new user (game) is manually. Also I hesitate to run it on mainnet, IMO still not production ready.

So the most important thing is feedback. I want to have understand what game developers need to build it in a suitable way

**Comment by adrianv425** [comment]
I cant wait to see it. I'm close to having a working prototype on mine. First feedback would be to make a route for CreateGame where it can take care of game creation. Simple fix but it's way better than manually inputting game info.

Also what exactly is nextPrize() for?

**Comment by leonprou** [comment]
Cool, please tell when it's ready!

> First feedback would be to make a route for CreateGame where it can take care of game creation.

Exactly what I did today :). See the last commits.

> Also what exactly is nextPrize() for?

`nextPrize` returns what's the prize now, meaning if someone  is winning right now that's gonna be his reward.. might be a bad name actually, better call it `currentPrize`..

**Comment by leonprou** [comment]
@adrianv425 So closing this for now, feel free to open new issues and reach us :)
